### ISSUE TITLE
Automatically create "published" state when creating a workflow

### ISSUE THREAD

**Issue by Buddhima** [joomla-projects/GSoC17_publishing_workflow#100]
### Suggestion

When creating a new workflow, a default state should be created automatically. 
State name: "published".

So that users will not get issue when creating first state (to make it default).

**Comment by bembelimen** [comment]
https://github.com/joomla-projects/GSoC17_publishing_workflow/commit/88a0198ac998eee858ed78288c7d78209fc86462
