### ISSUE TITLE
Add plugin trigger everywhere where it make sense

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/GSoC17_publishing_workflow#104]
@Buddhima perhaps anything for you?

**Comment by Buddhima** [comment]
Yes, we need to trigger events when transactions take place. So plugins will get trigger accordingly

**Comment by bembelimen** [comment]
Implemented here: https://github.com/joomla-projects/GSoC17_publishing_workflow/commit/b6a1429614df85c40f33745ca909a453cb41918f#diff-db94a7a8f9f1edf368d10d7b96302889R1127
