### ISSUE TITLE
We can't change the workflow of an article correct?

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/GSoC17_publishing_workflow#163]
### Steps to reproduce the issue

- create a new workflow != the default one
- create a category with the new workflow
- create a article in that category
- notice the supported workflow / states
- save and close
- change the category back to the default workflow
- check the article we have created before
- notice that still the "old" workflow is implemented.

### Expected result

Is this the expected behavior?

### Actual result

notice that still the "old" workflow is implemented.

**Comment by bembelimen** [comment]
This is expected behavior, Super Users can change the workflow via the batch process
