### ISSUE TITLE
Wrong time being saved for "Date Modified" at "Edit Workflow"

### ISSUE THREAD

**Issue by priiish** [joomla-projects/GSoC17_publishing_workflow#166]
### Steps to reproduce the issue
Go to Content / Workflows / Workflows. Klick on a Workflow to edit something about it. Press save and check the time at "Date Modified". It is two hours before the actual time at the moment of saving.

### Expected result
Date Modified should contain the exact time at the moment of saving.

### Actual result
Wrong time being saved.

### System information (as much as possible)
Chrome, Joomla! 4.0.0-dev

### Additional comments
<img width="1280" alt="bildschirmfoto 2018-07-26 um 13 21 20" src="https://user-images.githubusercontent.com/37930619/43259554-e9692ec8-90d6-11e8-83b9-0d68efb86896.png">

**Comment by bembelimen** [comment]
Joomla! saves the time as UTC +0, did you set the correct timezone in the global configuration?

**Comment by priiish** [comment]
Yup, probably was my mistake then. Sorry about that!

**Comment by priiish** [comment]
#issue can be closed
