### ISSUE TITLE
[PHPCS] 0.0.1-basic

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/GSoC17_publishing_workflow#27]
### Steps to reproduce the issue

Please take a look into: http://213.160.72.75/joomla-projects/GSoC17_publishing_workflow/36

This shows a list of things drone is not happy with ;)

### Expected result

Drone / PHPCs is happy.

### Actual result

Drone / PHPCs is  not happy.

**Comment by jjaracz** [comment]
Thanks, it seems phpcs is not work in my IDE :/ Maybe it is turned off, who knows.

**Comment by zero-24** [comment]
Maybe just the joomla rules are missing.
