### ISSUE TITLE
Add workflow view cancel button wrong validation issue

### ISSUE THREAD

**Issue by shubhamnba2009** [joomla-projects/GSoC17_publishing_workflow#30]
### Steps to reproduce the issue
1. Click on Content component and go to Workflows view and click on New button.

![1ststeppic](https://user-images.githubusercontent.com/12000068/27532160-f55782fc-5a7c-11e7-920c-8d6606602e7f.png)

2. Click on Title textbox. Don't write anything.

![2ndsteppic](https://user-images.githubusercontent.com/12000068/27532168-f9b05ab8-5a7c-11e7-956a-50ae2bb1cf93.png)

3. Click on Cancel button

### Expected result

The Workflows view screen must be shown without any validation error shown below "Title" text box 

### Actual result
"Field value cannot be empty" error comes after clicking on Cancel button below title text box.

![ezgif-1-39d1e909f7](https://user-images.githubusercontent.com/12000068/27532375-c26b3766-5a7d-11e7-9ab2-98586f6f867c.gif)

### System information (as much as possible)
Windows 8.1
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 
PHP extension: mysqli Documentation
PHP version: 5.6.21

**Comment by jjaracz** [comment]
I think that issue is with joomla itself :)

**Comment by bembelimen** [comment]
Only if the bug also appears in com_content...

**Comment by shubhamnba2009** [comment]
Hmm... The same thing happens in the Article view.. So I think this issue is with Joomla itself..

**Comment by bembelimen** [comment]
For me, the "article cancel button" works without problems

**Comment by jjaracz** [comment]
for sure you test it right? for me when i click on the title input and click cancel without clicking in other places, then is the same issue :)

**Comment by bembelimen** [comment]
Ah, now I get it...that has nothing to to with the cancel button. Every field will be validated on "blur", so the behavior is ok.
No need to fix this.

**Comment by shubhamnba2009** [comment]
Than lets close the issue 👍
