### ISSUE TITLE
Unordered ToDos (Evaluation 2)

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/GSoC17_publishing_workflow#32]
Category
- Deliver the default workflow with the installation
- Add a "use default" option to the category workflow select
- "Workflows" => "Workflow" in the category tab (singular)
- Filter for published workflows only

Workflow
- Add the filter functionality to the workflows view
  |- Search
  |- status (published/unpublished/trashed)
  |- Author
- Add ordering (also make the table headlines clickable)
- Remove "modification date" from the workflows view (but should remain in the db/form)
- add author
- Add publish/unpublish/trash toggle functionality
- Extend the form with publish state/author/dates
- Add toolbar buttons
- Description as editor field
- move default/publish/etc. in a right column (like articles)
- Add a default star" (like "home" in menu) to the list
- Load the com_content submenu on the left side, when the user is in the status/transition manager
- Default shouldn't be "on" as default

Perhaps (have to be discussed):
- Remove the "transitions" link in the list and rename the status link to "manage".

Status
- Here should also be filter/search/ordering (see above)
- Add description field
- Condition should be the (translated) text not the number in the status list
- The default state should be marked in the list (as star, see above)
- "Default" shouldn't be "on" as default
- Main menu is not correct in the status manager
- Add toolbar buttons

Transition
- Here should also be filter/search/ordering (see above)
- Description as editor field
- Clean up transition ACL (is everything required?)

Content
- Convert the status dropdown
- Convert the publishing icons in the list
- Add toolbar buttons

**Comment by jjaracz** [comment]
Category
- Deliver the default workflow with the installation **(You mean to deliver default workflow with all, states, transitions etc. ?)**
- Add a "use default" option to the category workflow select **(How "use defulat" should work? (That option we already have in the workflow)**
- "Workflows" => "Workflow" in the category tab (singular)
- Filter for published workflows only

Content
- Convert the status dropdown **(This too i don't fully understand :) )**
- Convert the publishing icons in the list **(To what icon i should change publishing icons?)**
- Add toolbar buttons **(Could you explain? To run more then one transition?)**

**Comment by bembelimen** [comment]
Category
> - Deliver the default workflow with the installation **(You mean to deliver default workflow with all, states, transitions etc. ?)**

Yes.
States: Published, Unpublished, Archived, Trashed
Transitions: P => U/A/T, U => P/T, A => T/P, T => P/U

> - Add a "use default" option to the category workflow select **(How "use defulat" should work? (That option we already have in the workflow)**

It should be an empty value and an article created in this category should use the default workflow

Content
> - Convert the status dropdown **(This too i don't fully understand :) )**

At the moment there is the default status dropdown in the form view, this should handle the new system

> - Convert the publishing icons in the list **(To what icon i should change publishing icons?)**

They should be the same, but use the conditions of the current status

> - Add toolbar buttons **(Could you explain? To run more then one transition?)**

Yes, to run transitions for more articles, but is a "nice to have". (Make sure, to remov the current "publish/unpublish" buttons

**Comment by jjaracz** [comment]
Category
- Deliver the default workflow with the installation
- Add a "use default" option to the category workflow select
- Filter for published workflows only

Content
- Convert the status dropdown
- Convert the publishing icons in the list
- Add toolbar buttons
