### ISSUE TITLE
[0.0.1-basic] Pushing to branch

### ISSUE THREAD

**Issue by jjaracz** [joomla-projects/GSoC17_publishing_workflow#38]
### Steps to reproduce the issue

I just try to push some commit to my branch

### Expected result

Code is on github at my branch

### Actual result

remote: Resolving deltas: 100% (42/42), completed with 38 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/0.0.1-basic.
remote: error: 2 of 2 required status checks are expected.
To https://github.com/joomla-projects/GSoC17_publishing_workflow
 ! [remote rejected]       0.0.1-basic -> 0.0.1-basic (protected branch hook declined)
error: failed to push some refs to 'https://github.com/joomla-projects/GSoC17_publishing_workflow'

**Comment by zero-24** [comment]
Yes i have protected that branch. If you use to directly commit there the status checks can't be done. I have disabled them now. So it should work again now.
