### ISSUE TITLE
2 Errors

### ISSUE THREAD

**Issue by jjaracz** [joomla-projects/GSoC17_publishing_workflow#43]
### Steps to reproduce the issue

Just go to the dashboard.

### Expected result

Everything is fine

### Actual result

I get that errors:

Notice: Undefined property: stdClass::$module in /home/janek/Dokumenty/GSoC/PublishingWorkflow/libraries/src/CMS/Helper/ModuleHelper.php on line 278

Notice: Undefined property: stdClass::$title in /home/janek/Dokumenty/GSoC/PublishingWorkflow/libraries/src/CMS/Helper/ModuleHelper.php on line 278

I was trying to find out what is going on, but i could not bind that messages with my code :/

### System information (as much as possible)

mysql: 5.6
php: 7.0

**Comment by bembelimen** [comment]
I updated Joomla! v4, the error should be fixed now.
