### ISSUE TITLE
Workflow states are not insert in to asset table

### ISSUE THREAD

**Issue by Buddhima** [joomla-projects/GSoC17_publishing_workflow#55]
### Steps to reproduce the issue

Create a new workflow state

### Expected result

Saving state should create a new entry in asset table

### Actual result
No entry is created

### System information (as much as possible)
Joomla installed on XAMPP with MySQL

**Comment by jjaracz** [comment]
![spectacle x13702](https://user-images.githubusercontent.com/8504663/28539859-699a25a6-70b3-11e7-9b67-ebbe1193a748.png)

**Comment by Buddhima** [comment]
Fixed with pull request: https://github.com/joomla-projects/GSoC17_publishing_workflow/pull/57
