### ISSUE TITLE
Transition Edit View shows trashed and archived states

### ISSUE THREAD

**Issue by Buddhima** [joomla-projects/GSoC17_publishing_workflow#60]
### Steps to reproduce the issue

Create a new workflow
Add some states
Make one of those trashed
Go to Transition creation view
Open the "From State" dropdown.

### Expected result
Trashed states should not be displayed

### Actual result
All the states created are in the dropdown

### System information (as much as possible)
Joomla installed on XAMPP with MySQL DB

**Comment by bembelimen** [comment]
Same could be for transitions + workflows itself, too (when they are displayed in a dropdown) => has to be checked
