### ISSUE TITLE
Issues with com_content

### ISSUE THREAD

**Issue by Buddhima** [joomla-projects/GSoC17_publishing_workflow#66]
### Steps to reproduce the issue

With the latest code base I have seen several issues in using com_content.

* Opening articles list view without any item shows following error
![image](https://user-images.githubusercontent.com/1543384/28755598-1b80550c-757c-11e7-8304-f944fa5d447d.png)

* Creating article fails with following error
![image](https://user-images.githubusercontent.com/1543384/28755602-424fe0b2-757c-11e7-9507-e4fe650a34ca.png)

These weren't there with previous code base.

### System information (as much as possible)

Joomla! installed on XAMPP, MySQL database

**Comment by jjaracz** [comment]
Yep, i know it, i was take that into account in summary :)
About second error, I forgot to remove workflow_id from installation script ... i will do it asap

**Comment by Buddhima** [comment]
Closing since those are fixed with recent changes.
