### ISSUE TITLE
Open issues

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/GSoC17_publishing_workflow#84]
# Article

- Workflow disable option is missing
- Transition and State Should be merged + an icon should indicate the condition (list + form)
- Transition dropdown should be formatted (custom-select e.g.)
- Trashed articles are still visible by default in the backend
- Perhaps we need a condition and a state filter? (grouped list?)

# Workflow
- Default workflow should have a create/modified date (+ Author?)
- I can deactivate the "default" status (in edit view) without setting a new one. (=> Check in PHP + deactivate the toggler when default is set)
- No need for "archive" status (button in the toolbar)

# States
- I can deactivate the default status (in edit view) => same as for workflows
- It's possible to create unpublished states which are marked as default (with the edit form)

**Comment by jjaracz** [comment]
>It's possible to create unpublished states which are marked as default (with the edit form)

I can not confirm that. Do you for sure choose status?

>Perhaps we need a condition and a state filter? (grouped list?)

I have created condition filter. What you mean by grouped list? There is that kind of input somewhere in Joomla?

**Comment by Buddhima** [comment]
Please see my test results (7/9/2017)

Article
-------

Workflow disable option is missing - NO IDEA
Transition and State Should be merged + an icon should indicate the condition (list + form) - FIXED
Transition dropdown should be formatted (custom-select e.g.) - FIXED (relates to previous)
Trashed articles are still visible by default in the backend - RELATED ISSUE #97, FIXED
Perhaps we need a condition and a state filter? (grouped list?) - FILTERS ARE THERE. BUT STATES ARE NOT GROUPED

Workflow
--------

Default workflow should have a create/modified date (+ Author?) - FIXED
I can deactivate the "default" status (in edit view) without setting a new one. (=> Check in PHP + deactivate the toggler when default is set) - FIXED
No need for "archive" status (button in the toolbar) - FIXED

States
-------

I can deactivate the default status (in edit view) => same as for workflows - FIXED, but this gives unpleasent feeling to user when creating the first state
It's possible to create unpublished states which are marked as default (with the edit form) - FIXED
