### ISSUE TITLE
Workflow states remain after deleting a state

### ISSUE THREAD

**Issue by Buddhima** [joomla-projects/GSoC17_publishing_workflow#85]
### Steps to reproduce the issue

Create a new workflow
Add some states and transactions
Delete a state

Transactions, coming-in or going-out of that state are getting deleted

#__workflow_transactions table entries getting deleted

### Expected result

#__asset table transaction entries should be removed

### Actual result

#__asset table transaction entries remain

### System information (as much as possible)

Joomla! on MySQL DB

**Comment by bembelimen** [comment]
Is resolved
