### ISSUE TITLE
Column ordering and Design

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/GSoC17_publishing_workflow#95]
I think the state is the first important thing to know (published, unpublished, trash) and should be a visible indicator in the first column. If you click on the indicator the transition dropdown opens. The Transition Dropdown should mention the state in brackets behind.

![image](https://user-images.githubusercontent.com/828371/29860512-925b8780-8d66-11e7-9541-438027ce3cf1.png)
Like this example you send me @bembelimen 

![image](https://user-images.githubusercontent.com/828371/29860532-a5b4573a-8d66-11e7-9604-2b207940d513.png)

The transition state itself should have limited characters. If you hover the state it can show the detailed description.

**Comment by Buddhima** [comment]
Remaining (7/9/2017)

* length of the drop-down should be fixed

**Comment by bembelimen** [comment]
Please check https://github.com/joomla-projects/GSoC17_publishing_workflow/pull/109 for first use case

**Comment by bembelimen** [comment]
The dropdown was fixed in the Jcore, so I think this Issue can be closed. If I missed something, please reopen.

Thanks @coolcat-creations for the ideas, all implemented ;)
