### ISSUE TITLE
Articles with a state which has the condition "trashed" should not be visible by default

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/GSoC17_publishing_workflow#97]
### Steps to reproduce the issue
Set the state of an article to something with the condition "trashed"

### Expected result
The article is not visible in the backend list by default

### Actual result
The article is still visible

**Comment by Buddhima** [comment]
* Reported issue fixed
* After trashing, when filter with state = 'trash' it is not visible. However when condition = 'trash' it is there.
* Thereafter (not sure exact reason) newly creating articles getting state = 0 in DB (Only for Uncategorized)

**Comment by bembelimen** [comment]
@Buddhima could you please confirm, that the last issue still exists and if so write a small step to step list so we can test?

**Comment by Buddhima** [comment]
@bembelimen : the last issue is no longer exist with current code-base. You may close this isse.
