### ISSUE TITLE
Fix article category list icon links

### ISSUE THREAD

**Issue by Buddhima** [joomla-projects/GSoC17_publishing_workflow#99]
### Steps to reproduce the issue
Following are links in category list view, for different filters in article list view

![image](https://user-images.githubusercontent.com/1543384/30176902-a77b1600-9421-11e7-898e-bb7ed8de19ca.png)

### Expected result
Links should direct to proper filters in article list view

### Actual result
Links are not directing to proper filters in article list view

### System information (as much as possible)
N/A

### Additional comments
N/A

**Comment by bembelimen** [comment]
Please check: https://github.com/joomla-projects/GSoC17_publishing_workflow/pull/116
